//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Clients')
export class ClientsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  Names: string;

  @Column('integer', { nullable: true })
  IDNumbers: number;

  @Column('text', { nullable: true })
  Address: string;

  @Column('text', { nullable: true })
  Emails: string;

  @Column('text', { nullable: true })
  PhoneNumbers: string;

  @Column('text', { nullable: true })
  Pictures: string;
}
