//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Payments')
export class PaymentsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  ServiceName: string;

  @Column('integer', { nullable: true })
  SenderName: number;

  @Column('real', { nullable: true })
  AmountReceived: number;
}
