//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Transactions')
export class TransactionsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  TransactionNumbers: string;

  @Column('integer', { nullable: true })
  SenderName: number;

  @Column('integer', { nullable: true })
  PictureOfSender: number;
}
