//Source code generated by AppGPT (www.appgpt.tech)
import { Admin, Resource, CustomRoutes } from 'react-admin';
import { customDataProvider } from './dataProvider';
import fakeDataProvider from 'ra-data-fakerest';
import { Dashboard } from './dashboard';
import { authProvider, apInitialize } from './authProvider';
import { i18nProvider } from './i18nProvider';
import LoginPage, { Login } from './Login';
import data from './data';
import { ClientsList, ClientsCreate, ClientsEdit } from './resources/Clients';
import {
  AccountsList,
  AccountsCreate,
  AccountsEdit,
} from './resources/Accounts';
import {
  TransactionsList,
  TransactionsCreate,
  TransactionsEdit,
} from './resources/Transactions';
import { LoansList, LoansCreate, LoansEdit } from './resources/Loans';
import {
  PaymentsList,
  PaymentsCreate,
  PaymentsEdit,
} from './resources/Payments';
import ClientsIcon from '@mui/icons-material/Person';
import AccountsIcon from '@mui/icons-material/AccountBox';
import TransactionsIcon from '@mui/icons-material/SwapHoriz';
import LoansIcon from '@mui/icons-material/AttachMoney';
import PaymentsIcon from '@mui/icons-material/Payment';
// SUPERTOKENS
import React from 'react';
import SuperTokens, {
  SuperTokensWrapper,
  getSuperTokensRoutesForReactRouterDom,
} from 'supertokens-auth-react';
import ThirdPartyPasswordless from 'supertokens-auth-react/recipe/thirdpartypasswordless';
import Session from 'supertokens-auth-react/recipe/session';
import { BrowserRouter, Routes, Route, Link } from 'react-router-dom';
import * as reactRouterDom from 'react-router-dom';
let sessionFn = Session.init();
SuperTokens.init({
  appInfo: {
    appName: import.meta.env.VITE_SUPERTOKENS_APPNAME,
    apiDomain: import.meta.env.VITE_BACKEND_DOMAIN,
    websiteDomain: import.meta.env.VITE_SUPERTOKENS_WEBSITEDOMAIN,
    apiBasePath: import.meta.env.VITE_BACKEND_APIPATH + '/auth',
    websiteBasePath: import.meta.env.VITE_SUPERTOKENS_WEBSITEBASEPATH,
  },
  recipeList: [
    ThirdPartyPasswordless.init({
      contactMethod: 'EMAIL',
      signInUpFeature: {
        providers: [
          ThirdPartyPasswordless.Github.init(),
          //ThirdPartyPasswordless.Google.init(),
          //ThirdPartyPasswordless.Facebook.init(),
          //ThirdPartyPasswordless.Apple.init(),
        ],
      },
    }),
    sessionFn,
  ],
});
apInitialize(Session);
// END SUPERTOKENS
let dataProvider: any;
if (import.meta.env.VITE_USE_BACKEND_DATA === 'true') {
  dataProvider = customDataProvider(
    import.meta.env.VITE_BACKEND_DOMAIN +
      import.meta.env.VITE_BACKEND_APIPATH +
      '/proxy',
  );
} else {
  dataProvider = fakeDataProvider(data.defaultData);
}

const App = () => (
  <SuperTokensWrapper>
    <BrowserRouter basename="/aa88c7a5e">
      <Admin
        authProvider={
          import.meta.env.VITE_ENVIRONMENT != 'DEV' ? authProvider : undefined
        }
        requireAuth
        loginPage={LoginPage}
        dataProvider={dataProvider}
        i18nProvider={i18nProvider}
        dashboard={Dashboard}
      >
        <Resource
          name="Clients"
          options={{ label: 'Clients' }}
          list={ClientsList}
          create={ClientsCreate}
          edit={ClientsEdit}
          recordRepresentation="Names"
          icon={ClientsIcon}
        />
        <Resource
          name="Accounts"
          options={{ label: 'Accounts' }}
          list={AccountsList}
          create={AccountsCreate}
          edit={AccountsEdit}
          recordRepresentation="AccountNumber"
          icon={AccountsIcon}
        />
        <Resource
          name="Transactions"
          options={{ label: 'Transactions' }}
          list={TransactionsList}
          create={TransactionsCreate}
          edit={TransactionsEdit}
          recordRepresentation="TransactionNumbers"
          icon={TransactionsIcon}
        />
        <Resource
          name="Loans"
          options={{ label: 'Loans' }}
          list={LoansList}
          create={LoansCreate}
          edit={LoansEdit}
          recordRepresentation="CreditReceivedAmount"
          icon={LoansIcon}
        />
        <Resource
          name="Payments"
          options={{ label: 'Payments' }}
          list={PaymentsList}
          create={PaymentsCreate}
          edit={PaymentsEdit}
          recordRepresentation="ServiceName"
          icon={PaymentsIcon}
        />
        <CustomRoutes noLayout>
          {/*This renders the login UI on the /auth route*/}
          {getSuperTokensRoutesForReactRouterDom(reactRouterDom)}
          {/*Your app routes*/}
        </CustomRoutes>
      </Admin>
    </BrowserRouter>
  </SuperTokensWrapper>
);

export default App;
